### ISSUE TITLE
404s on assets/resources

### ISSUE THREAD

**Issue by sonph** [dossist/moinmoin-memodump#22]
I've followed the instructions and installed the files but my web server is reporting 404s on asset files e.g. `404 GET /moin_static197/memodump/js/jquery.min.js` and the wiki page looks just like a HTML document without any CSS/JS. Can you help me with this issue?

Thanks for your work btw!

**Comment by dossist** [comment]
Hi, thanks for using memodump!

My apologies for your trouble. It seems that the resource files (javascripts and css) were copied to an wrong place, and MoinMoin couldn't find these files.
I came to notice that path to the resource directory `YourMoinDirectory/MoinMoin/web/static/htdocs/` could be different depending on how you installed MoinMoin.
1. Installed from repository/zip.
2. Installed from pre-packaged container maintained by Linux distributor.

In case 1, the cause could be simply a typo on directory path.
In case 2, the resource directory of MoinMoin could be in a different place. On Ubuntu Linux, it will be `/usr/share/moin/htdocs`.

In the right resource directory, there should be other directories for default themes such as `modernized`, `rightsidebar` and so on. If you find the right directory, copy resources of memodump into it.

Please note that if the resource directory of MoinMoin was `/usr/share/moin/htdocs`, that directory could only be writable for the superuser. Thus, you need a privilege to `sudo` or one to be the superuser. For example, if you could sudo,

```
sudo cp -a memodump /usr/share/moin/htdocs/
```

I hope this helps.

**Comment by sonph** [comment]
I followed the tutorial presented here: moinmo.in/HowTo/UbuntuQuick (installing from zip, version 1.9.7) and got MoinMoin working normally. `/usr/share/moin/htdocs` exists but copying into that folder didn't work; and copying to `/usr/local/lib/python2.7/dist-packages/MoinMoin/web/static/htdocs` worked. 
Issue resolved! Thanks!

**Comment by dossist** [comment]
Good to know that the issue is resolved. I will look into the installation process and update the description accordingly. Thanks for your report.
