### ISSUE TITLE
memodump does not respect user's editor type (text/gui) preference

### ISSUE THREAD

**Issue by sonph** [dossist/moinmoin-memodump#24]
Say a registered user prefers to use the GUI editor and he/she sets "Preferred Editor" to "gui" and "Editor shown on UI" to "the one preferred."

However memodump doesn't respect the setting because the Edit button URL is hardcoded to be `?action=edit&editor=text` instead of just `?action=edit` (in which case memodump does show the preferred editor).

**Comment by dossist** [comment]
Hi, fixed the issue in acb62d1e18e75aecc934224fed510bc8e512c038, by simply removing `editor=text` from the query string as you suggested.
Thanks for your help!

p.s. "Editor shown on UI" is still ignored though, for my preference. This option decides whether both text and gui editor links should be displayed or just what is preferred, so I believe ignoring it is not a big problem especially for this theme.

**Comment by sonph** [comment]
Issue fixed, thanks!

And btw in the installing instructions I think you could direct the users to clone this repository then symlink the files/folders instead of just copying them so that they could just pull the repository to update the theme.

**Comment by dossist** [comment]
That is a great idea. I will check if symlinks could pass security things on various environments, and add instructions.
