### ISSUE TITLE
[FeatureRequest] Confirmation on leaving edit mode with unsaved changes

### ISSUE THREAD

**Issue by sonph** [dossist/moinmoin-memodump#27]
It'd be helpful if you can implement a confirmation dialog when the user (accidentally) leaves the editor with unsaved changes (by pressing Back button, Cancel button, or by navigating to a different URL).

I am not familiar with the codebase and I have limited web dev skills so I'm asking you to do this if you don't mind.

Thanks!

**Comment by dossist** [comment]
While I really appreciate your attention and suggestions to the project, I'm not accepting feature requests. I'm sorry for that. :-(

For this particular subject, Chrome, Firefox and IE11 will throw a confirmation dialog when you leave the edit page with unsaved textarea (though they will not warn you if you click `Cancel` button). If you would come back to the edit page using forward/backward history of the browser, I guess you would still have your work. However, I'm afraid that IE will discard your work even if you navigate back in this way.
I hope this helps.

**Comment by sonph** [comment]
I'm actually using Chrome but I was editing in GUI mode, so I guess that was the reason why Chrome didn't throw me a confirmation dialog. Probably I'll just get my users to use the text editor then.

Perhaps in the future you could at least implement the feature for the Cancel button just in case the users accidentally click Cancel instead of Check Spelling.

I will also try looking into this. Thanks.
