### ISSUE TITLE
The default action revert is not available in the menu

### ISSUE THREAD

**Issue by LotekHeavy** [dossist/moinmoin-memodump#33]
Hi there

Not sure if it's a bug or my own mistake. I can view the old revision (recal) via info, but after that I do not see the feature "revert" in the "menu".

![revert-missing](https://cloud.githubusercontent.com/assets/7978295/3898432/33ab8766-226c-11e4-8ba4-b0407f04777e.jpg)

As far I understand it should not needed to edit the menu's (https://github.com/dossist/moinmoin-memodump/wiki/EditMenu), or I have to - do use the revert action?

thanks for any hints.

bye
Marcel

**Comment by dossist** [comment]
Hi, thanks for your attention.

The issue you described here was intended, but I think I should add _revert_ action now.
(I was not very familiar with how MoinMoin works when I wrote the default menu structure ;-)

I made a small change to the code to make the action available. (3c8c7f2d5320be4d7d56898ee2c2223df60eff13)
Now _revert_ will appear in the menu only when the page requested was one of revisions, to keep the menu as short as possible under normal view.
Thanks for pointing this out!

Best,
dossist
